# Generated by Django 3.2.7 on 2022-05-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='prewiew',
            new_name='preview',
        ),
    ]
